version: '3.9'

# TODO : utilisation des secrets

services:
  wordpress:
    image: ghcr.io/nykkolas/mon-cv-wordpress:${TAG:-latest}
    build: 
      context: ./wordpress
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    env_file: ./env/db.env
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    env_file: ./env/db.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wp:
    image: ghcr.io/nykkolas/mon-cv-wp:${TAG:-latest}
    build:
      context: ./wp
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    links:
      - db:mysql
    depends_on:
      - db
      - wordpress
    user: xfs # https://stackoverflow.com/questions/50999848/how-to-run-wp-cli-in-docker-compose-yml
    env_file: 
      - ./env/db.env
      - ./env/wordpress.env
    command: /bin/sh -eux /usr/src/wordpress/scripts/wp-init.sh

volumes:
  wordpress:
  db: