name: Manual Push containers
on:
  workflow_dispatch:

jobs:
  Call-Build-and-Test:
    uses: Nykkolas/mon-cv/.github/workflows/build-and-test.yml@master
    
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push dans GHCR
        run: docker compose push
