name: Pre-release
on:
  workflow_dispatch:
  
jobs:
  Push:
    runs-on: ubuntu-latest
    env:
      TAG: "latest"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and test
        run: sh ./build/build-and-test.sh

      - name: Push dans GHCR
        run: docker compose push

      - name: Build TAR
        run: sh ./build/create-package.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.TAG }}
          prerelease: true
          title: "Development Build"
          files: release/*
