name: Push containers
on:
  workflow_dispatch:
  
jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and test
        run: sh ./build/build-and-test.sh

      - name: Push dans GHCR
        run: docker compose push
