name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  
jobs:
  Push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Get Tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Set TAG environment variable
        run: echo "TAG=$GIT_TAG_NAME" >> $GITHUB_ENV

      - name: Show Tag name
        run: echo $TAG

      - name: Build and test
        run: sh ./build/build-and-test.sh

      - name: Push dans GHCR
        run: docker compose push

      - name: Build TAR
        run: sh ./build/create-package.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Development Build"
          draft: true
          files: release/*
